src/query.rs
src/world.rs
tests/tests.rs

These didn't account for queries that were safe on the same archetype.

Fix disjoint queries, strip out useless scope accessors

---

src/archetype.rs

Fixes #79. Though we properly drop the components themselves, the underlying memory was not recovered.

Fix memory leak in archetype resizing

---

src/archetype.rs

This PR adds a method with similar functionality to `Entity::component_types`, but on `Archetype`. This is useful for automating generation of scripting interfaces and schedules from archetypes.

Archetype::component_types

---

src/entities.rs
src/world.rs

This adds an unsafe method `World::resolve_unknown_gen` which allows the user to map a `u32` identifier extracted via `Entity::id` back to a potentially live `Entity`. As discussed previously it's unsafe because it may return a reference to a dead `Entity`, which will appear as though it has no components and may later spontaneously acquire components by becoming a live `Entity`.

Add `World::resolve_unknown_gen`

---

src/entities.rs
src/world.rs

This makes several changes:
- Cuts in half the number of atomic operations to reserve an Entity,
and simplifies the reservation code to no longer need a retry loop.
- Adds a new `reserve_entities` method that can reserve any number
of Entity IDs with a single atomic subtract.
- Removed the `reserved` and `free` arrays, which consumed
two u32 values for every Entity ID, and replaced them with a single
`pending` Vec. `pending` only needs one slot for every freed Entity.
- No longer dump huge lists of fresh IDs into the freelist when we
grow. The freelist only holds explicitly freed values, and we use
arithmetic to acquire new IDs.
- Removes the `reserved_len()`, etc. API used to flush reserved
entities. Now flush() takes a closure to initialize each entity.
- Tightened the restrictions on …

Rewrote concurrent entity allocations to be more efficient

---

src/archetype.rs
src/entity_builder.rs

TypeId is already a fully-hashed u64, so there is no need to hash it further.
Instead, just use nohash-hasher to pass it through unchanged.

Use a much faster hash for TypeId

---

src/archetype.rs

This is in new paranoia code that won't be run, because TypeId is u64,
but technically if TypeId changed to not be u64 or u128, and hashbrown
changed from ahash to use randomly-seeded hashes, then this would
compute ever-varying hashes for the same value. You can see this
if you replace the DefaultHashBuilder with RandomState.
Instead, construct hashbrown's default Hasher's using default().
This produces repeatable hashes even if using RandomState.

Nitpicking: don't create a new BuildHasher on each hash call

---

src/archetype.rs

ChunkIter calls `archetype.entities()` and `archetype.len()`.
By marking them `inline`, the outer loop of query iteration
avoids two function calls to these trivial methods (and the
register spills those cause).
This speeds up the iterate_100k benchmark by 23%. That feels
unreasonably high since it doesn't affect the innermost loop, but
even if this benefit is illusory the machine code is tighter so
this is a win.

Mark a couple archetype methods as `inline`

---

macros/src/lib.rs
src/archetype.rs
tests/derive.rs
tests/derive/generics.rs
tests/tests.rs

Fixes #87
This still does the duplication check, unlike tuples which don't do that. Should that stay or not?
Edit: Maybe the dupe check can be made cheaper by making it lazy and only execute once via AtomicBool and closures?

Support generics in bundle derive macro

---

src/entities.rs
src/world.rs

`spawn_at` takes an additional parameter of an Entity, to spawn the
corresponding entity at.  This can be useful if you're saving and
restoring gamestate in memory.  This can also be used to resurrect dead
entities references at will, presuming you have an old handle laying
around.

Adds spawn_at API to World.

---

benches/bench.rs
src/lib.rs
src/query.rs
src/query_one.rs
src/world.rs

These allow dynamic borrow checks to be bypassed when there's no concurrency needed. Confusingly, despite being literally the same iterator minus some setup work, the benchmark is ~50% slower. @mjhostet, am I doing something stupid here?

Methods for querying from a mutable borrow

---

src/archetype.rs
src/entity_builder.rs
src/lib.rs

Allows us to drop entities faster when needed and drastically
simplifies the implementation at the cost of occasional small padding
that the caller can avoid if they need to.

Store components aligned in EntityBuilder

---

CHANGELOG.md
Cargo.toml
src/entities.rs
src/lib.rs
src/serialize.rs
src/world.rs

hecs does not currently provide any tools to simplify serialization. I have personally argued that serialization done right tends to be highly application-specific, as users should take care to exclude runtime-only information like GPU resource handles, incorporate non-ECS data gracefully, and elide generation information from serialized entity IDs. In my own projects, I often convert entities or even entire worlds into a more serde-friendly format and serialize that, though this is suboptimal.
Users have frequently asked what the best approach for serialization with hecs is, and I set out to address that with an example. It became clear that any easily-implemented serialization scheme would be inefficient despite significant boilerplate, and an efficient scheme, avoiding redundant …

Serialization convenience

---

src/entity_builder.rs
tests/tests.rs

This is a pretty basic PR.  I contemplate adding `remove` functionality, but it was a lot more involved than this, and while I can think of use-cases I didn't find it very pressing to implement.  Let me know if you want me to update the PR with that functionality though.

Adds API surface to EntityBuilder to check and modify the current components of the builder.

---

Cargo.toml

`hashbrown` 0.10.0 has been yanked.

Downgrade hashbrown to 0.9.1

---

CHANGELOG.md
macros/src/query.rs
src/archetype.rs
src/batch.rs
src/borrow.rs
src/entities.rs
src/lib.rs
src/query.rs
src/world.rs
tests/tests.rs

Fixes #60. Allows for cache-efficient column-oriented custom operations such as (de)serialization.

Columnar component access

---

src/archetype.rs
src/batch.rs

This could otherwise cause strange behavior for empty archetypes with nonempty component sets.

Initialize archetype component state table in a valid state

---

src/entity_ref.rs
src/world.rs

Empty entities have a real archetype these days.

Remove special-cases from EntityRef

---

macros/src/bundle.rs
src/bundle.rs
src/entity_builder.rs
src/lib.rs
src/world.rs

This gets a start on #142, making a decent performance improvement for typical single-entity spawns.

Cache bundle -> archetype lookup on spawn

---

src/archetype.rs
src/world.rs

While looking into #154, I noticed that `TypeIdMap` was used in some but not all possible places where hash tables keyed by type ID were used.

Consistently apply TypeIdMap optimization where possible

---

macros/src/query.rs
src/query.rs
tests/derive/enum.rs
tests/derive/enum.stderr
tests/derive/union.rs
tests/derive/union.stderr
tests/tests.rs

Fixes #161.
Not a huge fan of how this complicates `Fetch`, but it fixes the unsoundness and has no overhead in practice.

Fix query_mut permitting unsound double-borrows

---

src/query.rs
tests/tests.rs

There should be no soundness issue here as the borrows can only be narrowed by transforming a query after having iterated it and the lifetime narrowing on the iterator itself will prevent keeping the references it yields around until a second iterator can be derived.
The test case `alias` was indeed not really testing aliasing as it never used the references stored in `_a` and `_b` with overlapping lifetimes.

Allow deriving more than one iterator from a query borrow

---

benches/bench.rs
examples/ffa_simulation.rs
macros/src/query.rs
src/archetype.rs
src/batch.rs
src/entity_ref.rs
src/lib.rs
src/query.rs
src/query_one.rs
src/world.rs
tests/tests.rs

This uses a separately managed query cache that checks both the memory address of the archetypes as well as the generation number to ensure that the cache its keeping belongs to the same world and in the same state as the query it is backing. (There might be an ABA problem here, e.g. world A adds archetypes until generation N, caches are query, adds more archetypes and reallocates that `Vec`, then world B adds archetypes until generation N which are backed by the same allocation that was dropped by world A after caching a query. Uniquely tagging worlds using an `AtomicUsize` instead might resolve this.)
The main issue I currently see is that the performance does not seem to improve measurably, e.g.
```
test iterate_cached_100k_by_50   ... bench:      22,605 ns/iter (+/- 556)
test …
```

Introduce an out-of-line query cache storing matching archetypes

---

src/query.rs
src/world.rs
tests/derive/wrong_lifetime.stderr

We neglected to populate the entity's location metadata properly. The test passed because archetype-driven iteration still worked fine.

Fix random access in column-deserialized worlds

---

src/lib.rs

Exports the  error type for `query_one_mut`. The error type for `query_one` is already exported.

Reexport QueryOneError

---

CHANGELOG.md
benches/bench.rs
src/entity_builder.rs
src/lib.rs

This is convenient for storing dynamic entity prototypes, which may be used to efficiently spawn individual identical entities on a recurring basis.
Fixes #193.
There's one aspect of the current draft I'm not happy with: a double indirect function call per component when building an entity from a cloneable builder. There's no escaping at least one indirect call per component, but it'd be nice not to have two. This is difficult because we need temporary storage for the cloned component value so that we can construct a pointer to it in `DynamicBundle::put` which the caller can move out of. If we refactored `DynamicBundle::put` to take pointers to write into instead, bundles would have to handle random access by `TypeId`, which is awkward and might compromise performance. Maybe we should …

Cloneable component specialization of EntityBuilder

---

src/bundle.rs
src/entity_builder.rs
src/world.rs
tests/tests.rs

This fixes issue #211 without any apparent breakages in the public API, allowing for an immediate patch release.
The commit also adds appropriate tests for the cloneable entity builder which were previously missing.

Add EntityBuilderClone::add_bundle and tests

---

benches/bench.rs
src/lib.rs
src/query.rs
tests/tests.rs

This is basically a generalisation of the `World::column(_mut)` API for arbitrary queries involving multiple components and/or query combinators.

Add query map providing random access to query results

---

macros/src/bundle.rs
src/bundle.rs
src/world.rs

I think the first commit is almost certainly an improvement as the bundles will usually contain very few types so the binary search almost certainly preferable to the ahash-based `HashSet` in terms of code size and thereby performance. The second one might be pushing it though as the dynamic allocation is done only in the slow path in the first place. The modified method `Bundle::with_static_type_info` might become generally useful in the future though, at the cost of changing the theoretically user-facing API now.

RFC: Streamline computation of component removal target archetype

---

src/world.rs

We ran into this during modelling and were confused, so thought it would be nice to at least clarify this in the documentation.
(Fixing it would most likely make `World::clear` significantly more costly to implement as all generations would need to be bumped, ideally except for those already on the free list.)
cc @mlange-42

Clarify that using World::clear will lead to entity ID repeating.

---

CHANGELOG.md
src/serialize/column.rs
src/serialize/row.rs

Gives more flexibility to implementers, allowing e.g. cheeky type erasure tricks.

Pass serializers by value to serializer context traits

---

src/query.rs

Borrow checking is done at .query() time. Safe to send/share between threads as there is no interior mutability here.

impl Send and Sync for View

---

src/entities.rs
src/world.rs

When the `id` of a dangling Entity is larger than any previously allocated from the world, `Entities::get` would erroneously judge it to be pending, leading `insert` to attempt access to out-of-bounds location or archetype data.
Replicates the same fix applied in https://github.com/Ralith/hecs/pull/244 to `Entities::get`. `get_mut` is left as-is as it doesn't handle pending entities.

Fix panic on inserting with some dangling Entity handles

---

examples/ffa_simulation.rs

Fix a minor typo in an example file: `enity` -> `entity`

fix typo in ffa_simulation.rs enity -> entity

---

CHANGELOG.md
README.md
examples/ffa_simulation.rs
examples/format.rs
src/archetype.rs
src/command_buffer.rs
src/entity_builder.rs
src/entity_ref.rs
src/lib.rs
src/query.rs
src/query_one.rs
src/serialize/column.rs
src/serialize/row.rs
src/world.rs
tests/tests.rs

Many users have reported confusion arising from the use of component types in `World::get` in contrast to the use of reference sin `World::query` and friends. This replaces `get` and `get_mut` on `World` and `EntityRef` with a single `get` that is generic over *references to components*, so that the intuitive thing Just Works, and passing an explicit component type generates a trait error.
For consistency, `EntityBuilder:;get` and `get_mut` are both refactored similarly, although they cannot be combined into a single method as they do not perform dynamic borrow checking.
This also resolves the inconsistency between `get_mut` referring to the mutability of the component borrow, while other `_mut` methods on `World` instead refer to the mutability of the world borrow.

Refactor World::get to take reference types

---

CHANGELOG.md
src/query.rs
tests/tests.rs

Saves some atomics and makes cheeky overlapping queries more reliable.

Don't borrow-check empty archetypes

---

CHANGELOG.md

These methods were removed in hecs 0.8.0 (in #274), but previously, their removal wasn't explicitly mentioned in the changelog. This commit mentions them by name, which should make the upgrade path to `World::get`/`EntityRef::get` a bit clearer.
Fixes #284.

Add removal of `World::get_mut` and `EntityRef::get_mut` to the changelog

---

examples/format.rs
tests/derive.rs
tests/tests.rs

Fixed the various lints clippy throws right now. Some of these are uglier fixes, but it makes working in this repo nicer by reducing warnings.

clippy lints fixed

---

src/query.rs

`Satisfies` does not exclude any entities.

Fix `Satisfies` query access mode

---

CHANGELOG.md
src/archetype.rs
src/entity_ref.rs
tests/tests.rs

This commit adds analogues of [std::cell::Ref::map](https://doc.rust-lang.org/stable/std/cell/struct.Ref.html#method.map) and [std::cell::RefMut::map](https://doc.rust-lang.org/stable/std/cell/struct.RefMut.html#method.map), which allow the contents of a `Ref`/`RefMut` to be transformed without reborrowing. This can make it easier to write certain kinds of functions which return data borrowed from components.
An example of this kind of code is below:
```rust
trait MyComponentTrait {
fn get_state(&self) -> &dyn MyState;
}
fn entity_get_state<T: MyComponentTrait>(ent: EntityRef<'_>) -> Option<Ref<'_, dyn MyState>> {
let component = ent.get::<&'_ T>();
component.map(|comp_ref| Ref::map(comp_ref, |comp| comp.get_state()))
}
struct MyComponentInstance {
// state unspecified...
}
impl …
```

Add `Ref::map` and `RefMut::map`.

---

macros/src/query.rs

Rather than giving the Fetch/State types names unlikely to collide, we can introduce fully hygenic names by moving the type definitions and the trait impls that depend on them into an anonymous scope.
This was intended as groundwork for making `derive(Query)` work for queries where `Query::Item` and `Self` structurally differ (like `Without`) but that makes it impossible to derive attributes for the query item, which seems suboptimal. Still, useful cleanup.

Don't clutter caller namespace with derive(Query) internals

---

src/archetype.rs
src/lib.rs
src/query.rs
src/world.rs

Stumbled across some major speedups while chipping away at #334. Iteration of large archetypes is now ~twice as fast, with no significant change elsewhere.
Before:
```
test iterate_100k                   ... bench:     130,153 ns/iter (+/- 12,301)
test iterate_cached_100_by_50       ... bench:       1,010 ns/iter (+/- 75)
test iterate_mut_100k               ... bench:     127,847 ns/iter (+/- 6,311)
test iterate_mut_cached_100_by_50   ... bench:         251 ns/iter (+/- 58)
test iterate_mut_uncached_100_by_50 ... bench:         602 ns/iter (+/- 138)
test iterate_uncached_100_by_50     ... bench:       2,146 ns/iter (+/- 44)
```
After:
```
test iterate_100k                   ... bench:      51,880 ns/iter (+/- 2,813)
test iterate_cached_100_by_50       ... bench:         957 ns/iter (+/- …
```

Optimize iteration

---

.github/workflows/rust.yml
src/query.rs

This fixes the clippy error in CI, uses last version of actions and removes/replaces deprecated ones

Improve CI

---

tests/no-std-test-crates/macros/src/lib.rs

very minor change, but makes working in the repo nicer if you have clippy auto-running since there aren't 2 warnings always

clippy yells no more

---

CHANGELOG.md
src/query.rs
src/world.rs
tests/tests.rs

CC @sanbox-irl
Bikeshed: It's a bit unfortunate that `View::get_mut_n` is named in a different pattern, but `query_one_mut_n` would be really silly. `query_n_mut` is also a possibility, but is inconsistent with the proposed std [`[T]::get_many_mut`](https://doc.rust-lang.org/std/primitive.slice.html#method.get_many_mut), and if we're going to be internally inconsistent, we might as well take the opportunity to mirror std.

Introduce World::query_many_mut

---

src/change_tracker.rs
src/lib.rs

Much like `CommandBuffer` and serialization support, I think this is non-obvious, useful, and self-contained enough to merit inclusion even though it's implemented purely in terms of the public API. I'm interested in feedback on whether this would indeed be useful to people, and on the API design, including the detailed semantics.

Introduce change tracking helper

---

src/lib.rs
src/query.rs
src/world.rs
tests/tests.rs

view on world

---

.gitignore
Cargo.toml
examples/serialize_to_disk.rs

As discussed in https://github.com/Ralith/hecs/issues/380

Add World serialization example

---

README.md
benches/bench.rs
macros/src/lib.rs
src/archetype.rs
src/borrow.rs
src/bundle.rs
src/command_buffer.rs
src/entity_builder.rs
src/lib.rs
src/query.rs
src/world.rs
tests/tests.rs

Google has disclaimed ownership of hecs copyright, so we can tidy up.

Remove Google boilerplate

---

Cargo.toml
benches/bench.rs

bencher is difficult to profile as it exposes no control over runtime.

Migrate benchmarks to criterion

---

src/archetype.rs
src/batch.rs
src/query.rs
src/world.rs
tests/tests.rs

Fixes https://github.com/Ralith/hecs/issues/399, https://github.com/Ralith/hecs/issues/155.
Remaining work:
- Use the cache to drive borrows
- Validate with benchmarks
- Expand use of the cache to other query methods
- Cache views too?

Cache queries automatically
