- Cargo.toml
- src/borrow.rs
Removes the parking_lot dependency.
> Implement BorrowState from scratch

- Cargo.toml
- macros/src/lib.rs
- src/archetype.rs
- src/borrow.rs
- src/bundle.rs
- src/entity_builder.rs
- src/lib.rs
- src/query.rs
- src/world.rs
> Add #[no_std] support

- src/archetype.rs
> Fix confused values in moved entity renumbering

- src/query.rs
Improves readability of complex queries
> Reverse argument order to With/Without

- src/query.rs
- src/world.rs
> Restore query combinators and cite from World::query

- examples/format.rs
> Provide an entity formatting example

- src/query.rs
- src/world.rs
- tests/tests.rs
> Batched query iterators

- src/archetype.rs
- src/lib.rs
- src/query.rs
- src/world.rs
CC @Ratysz. This needs review for semantic correctness which I'm too sleepy to give it at the moment.
> Refactor and expose query archetype access

- .github/workflows/rust.yml
> Use cargo miri setup rather than installing xargo manually

- src/lib.rs
- src/query_one.rs
- src/world.rs
- tests/tests.rs
Still considering whether this is worth having.
> Support querying a single entity

- README.md
- src/lib.rs
> Tweak introductory example and copy it into the README

- macros/src/lib.rs
- tests/tests.rs
> Resolve clippy lints

- src/query.rs
This makes the iterate_100k benchmark more than twice as fast!
> Reduce branching in query iteration

- src/query.rs
- src/query_one.rs
> Query optimization

- src/query.rs
Loops using QueryIter spend time zero-extending u32 values to usize
so they can be used in address computations. There's no need to save
memory for iterator fields, since iterators are transient, so instead
just widen them to usize, which is more natural.
This drops the inner loop for the iterate_100k benchmark from this:
```
loop:
mov    %esi,%eax
movss  (%r14,%rax,4),%xmm0
addss  0x0(%rbp,%rax,4),%xmm0
add    $0x1,%esi
movss  %xmm0,0x0(%rbp,%rax,4)
mov    0x30(%rsp),%rax
mov    %rax,(%rsp)
mov    0x38(%rsp),%r13
cmp    %ecx,%esi
je     done
test   %rbp,%rbp
jne    loop
done:
```
to this:
```
loop:
movss  (%r14,%rsi,4),%xmm0
addss  0x0(%rbp,%rsi,4),%xmm0
movss  %xmm0,0x0(%rbp,%rsi,4)
add    $0x1,%rsi
test   %rbp,%rbp
je     done
cmp    %rcx,%rsi
jne    loop
done:
```
Resulting in a 29% …
> Use `usize` rather than `u32` in QueryIter to avoid zero extensions

- src/query.rs
LLVM seems to get confused by the use of consts for the `DANGLING`
structs; it's hard to see what's going on but perhaps it's losing track of
the nonnull properties of some fields, even though they are constants?
In any case, it handles equivalent functions just fine, so use those instead.
There is naming precedent with `NonNull::dangling()` anyway.
This drops the inner loop for iterate_100k from this (note the bizarre test
of the base pointer we just dereferenced against null):
```
loop:
movss  (%rsi,%rbp,4),%xmm0
addss  (%rcx,%rbp,4),%xmm0
movss  %xmm0,(%rcx,%rbp,4)
add    $0x1,%rbp
test   %rcx,%rcx
je     done
cmp    %rdi,%rbp
jne    loop
```
to this:
```
loop:
movss  (%rsi,%rax,4),%xmm0
addss  (%r12,%rax,4),%xmm0
movss  %xmm0,(%r12,%rax,4)
add    $0x1,%rax
cmp    %rdi,%rax
jne    loop …
```
> Use functions rather than consts for DANGLING values

- macros/Cargo.toml
- macros/src/bundle.rs
- macros/src/lib.rs
- macros/src/query.rs
- src/lib.rs
- tests/derive.rs
- tests/derive/enum.rs
- tests/derive/enum.stderr
- tests/derive/export.rs
- tests/derive/named_structs.rs
- tests/derive/nested_query.rs
- tests/derive/no_prelude.rs
- tests/derive/tuple_structs.rs
- tests/derive/union.rs
- tests/derive/union.stderr
- tests/derive/wrong_lifetime.rs
- tests/tests.rs
Monomorphic structs only, but otherwise fairly unrestricted.
> derive(Query) support

- macros/src/bundle.rs
- macros/src/query.rs
- src/entities.rs
Fixes #133. Looks like this was a pretty simple omission.
@mjhostet would love a sanity check from you!
> Fix length tracking for unallocated reserved entities

- CHANGELOG.md
- benches/bench.rs
- src/serialize/column.rs
- src/serialize/mod.rs
- src/serialize/row.rs
More compact and compressible, but less human-friendly.
> Columnar serialization

- CHANGELOG.md
- benches/bench.rs
- macros/src/bundle.rs
- src/archetype.rs
- src/bundle.rs
- src/entity_builder.rs
- src/lib.rs
- src/world.rs
> Implement archetype transform graph optimization

- src/query.rs
I am currently trying to figure out how to implement #154 and noticed that `QueryIter::len` seems to yield the overall number of items instead of yielding only those items remaining as required by the contract of [Iterator::size_hint](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.size_hint). I tried fixing this by changing the implementation to use a slice iterator (which also reduces the size of `QueryIter`) and considering the remaining items of the current chunk.
I then made the same modification for `BatchedIter` as a separate commit to keep things consistent, even though I do not think it necessarily improves that implementation.
> Use slice iterator in QueryIter implementation

- CHANGELOG.md
- src/entity_ref.rs
- src/serialize/column.rs
- src/serialize/row.rs
- src/world.rs
Fixes https://github.com/Ralith/hecs/issues/164
> EntityRef::entity accessor for recovering the entity's handle

- src/archetype.rs
The shared memory is behind a raw pointer, which reference visibility semantics don't see through. See https://github.com/bevyengine/bevy/pull/2172 for discussion.
> Remove meaningless UnsafeCell

- src/archetype.rs
- src/batch.rs
- src/world.rs
> Apply exponential resize strategy to reserve 

- CHANGELOG.md
- src/entities.rs
- src/entity_ref.rs
- src/world.rs
- tests/tests.rs
> Fix panic on certain operations involving empty entities

- src/archetype.rs
At this cost of one additional indirection when accessing an archetype, this simplifies unsafe code and saves reallocating the type state table when growing. Additionally, it lowers the barrier to exploring heterogeneous component layout/encoding in future work.
The critical tight-loop iteration performance is totally unaffected, as it still boils down to indexing through one pointer per component type.
> Store components in separate allocations

- src/archetype.rs
Replaces binary search with indexing for many operations
> Colocate borrow state with component storage pointers

- src/lib.rs
- src/query.rs
- tests/tests.rs
> Inclusive Or query combinator

- Cargo.toml
- src/entities.rs
- src/world.rs
fixes #204 
Is this what you had in mind @Ralith ? Not too familiar with the spin mutex you recommended or the initialization your variable needs but I gave it my best shot.
> Replace usage of AtomicU64 and AtomicI64 for MIPS and PPC compatibility

- src/archetype.rs
> Make TypeInfo's accessors public and add a from_parts constructor

- .github/workflows/rust.yml
- src/entity_builder.rs
This has been a persistent source of pain due to error message changes
breaking trybuild, for no benefit.
> Don't run CI on beta rust

- macros/src/bundle.rs
- macros/src/bundle_clone.rs
- macros/src/common.rs
- macros/src/lib.rs
- src/bundle.rs
- src/lib.rs
- src/world.rs
- tests/tests.rs
Note: `DynamicClone::new` has to be visibile outside the crate in order to be used in the macro.
Fixes issue #214
> Add `DynamicBundleClone` derive macro

- src/column.rs
Use that the base pointer depends only on the archetype but not on the entity within it in the implemenation of Column(Mut).
> Optimise Column(Mut

- Cargo.toml
> Add explicit MSRV to Cargo.toml

- src/lib.rs
- src/query.rs
- tests/tests.rs
> RFC: Add View::get_mut_n as a safe alterantive to View::get_mut_unchecked.

- src/query.rs
- src/world.rs
So the generation is essentially the number of archetypes.
> Archetypes are always added, never removed

- src/entity_builder.rs
- tests/tests.rs
Fixes https://github.com/Ralith/hecs/issues/253
> Fix Clone impl for EntityBuilderClone/BuiltEntityClone

- src/entities.rs
> Fix spawn_at creating phantom entities

- src/serialize/column.rs
Fixes https://github.com/Ralith/hecs/issues/268.
> Fix incorrect component counts in column serialization

- macros/src/bundle.rs
(cherry picked from commit 0926b239e84933c7a36a4d0d79e62d68fd125ddc)
> Fix cippy lint in derive(Bundle)

- src/query.rs
- tests/derive/wrong_lifetime.stderr
- tests/tests.rs
> Implement into_iter_batched for QueryMut

- Cargo.toml
- macros/src/query.rs
- src/lib.rs
- src/query.rs
- src/query_one.rs
- src/world.rs
- tests/derive/wrong_lifetime.stderr
Decent cleanup and clarity improvement. Waiting on 1.65 release.
> Replace QueryItem with a GAT

- CHANGELOG.md
- src/query.rs
- src/query_one.rs
- src/world.rs
- tests/tests.rs
> Fix World::{query_one, query_one_mut} violating unique borrow.

- src/command_buffer.rs
> Fix entity concatenation when some CommandBuffer inserts fail

- src/query.rs
> Clarify docs for `With`, `Without`, and `Satisfies`

- examples/transform_hierarchy.rs
Demonstrates the use of some more advanced features to efficiently solve a common problem.
> Add transform hierarchy example

- src/archetype.rs
Fixes https://github.com/Ralith/hecs/issues/347.
> Check for alloc failure before copying

- src/entities.rs
I noticed a few atomic loads and stores could be eliminated in `entities.rs` because mutable access to `free_cursor` is available.
> Use `AtomicIsize::get_mut` where appropriate

- CHANGELOG.md
- examples/cloning.rs
- src/archetype.rs
- src/batch.rs
- src/lib.rs
And expose necessary APIs.
Based on discussions in #372.
> Add World Clone example

- src/archetype.rs
- tests/derive/wrong_lifetime.stderr
Fixes for 2 failures that popped up in CI thanks to the Rust 1.86 release.
> Rust 1.86 fixes
